const PRODUCTS = [
  // Jaggery
  {
    id: 1,
    name: "Jaggery Powder",
    image: "/products/Jaggery/jaggery-powder.png",
    price: 60,
    rating: 4.8,
    unit: "500g",
    category: "Jaggery",
    isBestSeller: true,
  },
  {
    id: 2,
    name: "Jaggery",
    image: "/products/Jaggery/jaggery.jpeg",
    price: 60,
    rating: 4.7,
    unit: "500g",
    category: "Jaggery",
  },
  {
    id: 3,
    name: "Herbal Jaggery Powder",
    image: "/products/Jaggery/herbal-jaggery-powder.jpeg",
    price: 85,
    rating: 4.9,
    unit: "500g",
    category: "Jaggery",
  },

  // Rock Salt
  {
    id: 4,
    name: "Himalayan Rock Salt crystal",
    image: "/products/Rock Salt/hiamalayan-rock-salt-crystal-1000g.jpeg",
    price: 110,
    rating: 4.6,
    unit: "1000g",
    category: "Rock Salt",
    isBestSeller: true,
  },
  {
    id: 5,
    name: "Himalayan Rock Salt crystal",
    image: "/products/Rock Salt/hiamalayan-rock-salt-crystal-500g.jpeg",
    price: 55,
    rating: 4.5,
    unit: "500g",
    category: "Rock Salt",
  },
  {
    id: 6,
    name: "Himalayan Rock Salt - Free flow",
    image: "/products/Rock Salt/hiamalayan-rock-salt-pink-1000g.jpeg",
    price: 100,
    rating: 4.7,
    unit: "1000g",
    category: "Rock Salt",
  },
  {
    id: 7,
    name: "Himalayan Rock Salt - Free flow",
    image: "/products/Rock Salt/hiamalayan-rock-salt-pink-500g.jpeg",
    price: 55,
    rating: 4.6,
    unit: "500g",
    category: "Rock Salt",
  },

  // Palm candy
  {
    id: 8,
    name: "Palm Candy Normal",
    image: "/products/Palm candy/palm-candy-normal-100g.jpeg",
    price: 50,
    rating: 4.7,
    unit: "100g",
    category: "Palm candy",
  },
  {
    id: 9,
    name: "Palm Candy Normal",
    image: "/products/Palm candy/palm-candy-normal-250g.jpeg",
    price: 100,
    rating: 4.8,
    unit: "250g",
    category: "Palm candy",
    isBestSeller: true,
  },
  {
    id: 10,
    name: "Palm Candy Premium",
    image: "/products/Palm candy/palm-candy-premium-100g.jpeg",
    price: 80,
    rating: 4.9,
    unit: "100g",
    category: "Palm candy",
  },
  {
    id: 11,
    name: "Palm Candy Premium",
    image: "/products/Palm candy/palm-candy-premium-250g.jpeg",
    price: 175,
    rating: 4.8,
    unit: "250g",
    category: "Palm candy",
  },
  {
    id: 12,
    name: "Palm Candy Export",
    image: "/products/Palm candy/palm-candy-premium-250g.jpeg",
    price: 335,
    rating: 4.9,
    unit: "500g",
    category: "Palm candy",
  },

  // Peanut Chikki
  {
    id: 13,
    name: "Peanut Chikki Normal",
    image: "/products/Peanut Chikki/peanut-chikki-normal-200g.png",
    price: 70,
    rating: 4.9,
    unit: "200 gm",
    category: "Peanut Chikki",
    isBestSeller: true,
  },
  {
    id: 14,
    name: "Peanut Chikki Nice",
    image: "/products/Peanut Chikki/peanut-chikki-nice-200g - Copy.jpeg",
    price: 70,
    rating: 4.8,
    unit: "200 gm",
    category: "Peanut Chikki",
  },
  {
    id: 15,
    name: "Peanut Chikki Balls",
    image: "/products/Peanut Chikki/peanut-chikki-balls-80g.jpeg",
    price: 30,
    rating: 4.7,
    unit: "80 gm",
    category: "Peanut Chikki",
  },
  {
    id: 16,
    name: "Black Sesame Balls",
    image: "/products/Peanut Chikki/black-sesame-balls-50g.jpeg",
    price: 30,
    rating: 4.8,
    unit: "50 gm",
    category: "Peanut Chikki",
  },
  {
    id: 17,
    name: "Fried Gram Balls",
    image: "/products/Peanut Chikki/fried-gram-balls-60g.jpeg",
    price: 25,
    rating: 4.6,
    unit: "60 gm",
    category: "Peanut Chikki",
  },
  {
    id: 18,
    name: "Peanut Chikki Normal Jar",
    image: "/products/Peanut Chikki/peanut-chikki-normal-jar.jpeg",
    price: 150,
    rating: 4.9,
    unit: "30 Pcs",
    category: "Peanut Chikki",
  },
  {
    id: 19,
    name: "Peanut Chikki Normal Nice Jar",
    image: "/products/Peanut Chikki/peanut-chikki-normal-jar.jpeg",
    price: 150,
    rating: 4.8,
    unit: "30 Pcs",
    category: "Peanut Chikki",
  },
  {
    id: 20,
    name: "Black Sesame Jar",
    image: "/products/Peanut Chikki/peanut-chikki-normal-jar.jpeg",
    price: 150,
    rating: 4.7,
    unit: "30 Pcs",
    category: "Peanut Chikki",
  },

  // Honey Products
  {
    id: 21,
    name: "Hill honey or malai then",
    image: "/products/Honey Products/hill-honey.png",
    price: 80,
    rating: 4.9,
    unit: "100 g",
    category: "Honey Products",
  },
  {
    id: 22,
    name: "Hill honey or malai then",
    image: "/products/Honey Products/hill-honey.png",
    price: 160,
    rating: 4.8,
    unit: "250 g",
    category: "Honey Products",
    isBestSeller: true,
  },
  {
    id: 23,
    name: "Hill honey or malai then",
    image: "/products/Honey Products/hill-honey.png",
    price: 300,
    rating: 4.9,
    unit: "500 g",
    category: "Honey Products",
  },
  {
    id: 24,
    name: "Honey with Dry fruits",
    image: "/products/Honey Products/honey-with-dry-fruits.jpeg",
    price: 240,
    rating: 4.8,
    unit: "250 g",
    category: "Honey Products",
  },
  {
    id: 25,
    name: "Honey with dry fig",
    image: "/products/Honey Products/hone-with-dry-fig.png",
    price: 240,
    rating: 4.9,
    unit: "250 g",
    category: "Honey Products",
  },
  {
    id: 26,
    name: "Rose Honey or Kulkandth",
    image: "/products/Honey Products/rose-honey-100g.jpeg",
    price: 90,
    rating: 4.7,
    unit: "100 g",
    category: "Honey Products",
  },
  {
    id: 27,
    name: "Rose Honey or Kulkandth",
    image: "/products/Honey Products/rose-honey-250g.jpeg",
    price: 175,
    rating: 4.8,
    unit: "250 g",
    category: "Honey Products",
  },
  {
    id: 28,
    name: "Honey Amla Cut pcs",
    image: "/products/Honey Products/honey-amla-cut-pcs.png",
    price: 110,
    rating: 4.6,
    unit: "150 g",
    category: "Honey Products",
  },
  {
    id: 29,
    name: "Honey Amla Pouch",
    image: "/products/Honey Products/honey-amla-single-pc-box.jpeg",
    price: 120,
    rating: 4.7,
    unit: "250 g",
    category: "Honey Products",
  },
  {
    id: 30,
    name: "Honey Amla Single Pcs box",
    image: "/products/Honey Products/honey-amla-single-pc-box.jpeg",
    price: 300,
    rating: 4.8,
    unit: "20 Pcs",
    category: "Honey Products",
  },

  // Millet Cookies
  {
    id: 31,
    name: "Millet ghee cookies",
    image: "/products/Millet Cookies/millet-ghee-cookies.png",
    price: 65,
    rating: 4.8,
    unit: "140 g",
    category: "Millet Cookies",
    isBestSeller: true,
  },
  {
    id: 32,
    name: "Millet honey cookies",
    image: "/products/Millet Cookies/millet-honey-cookies.png",
    price: 65,
    rating: 4.7,
    unit: "140 g",
    category: "Millet Cookies",
  },

  // Millet Laddu
  {
    id: 33,
    name: "Pearl Millet laddu Box",
    image: "/products/Millet Laddu/pearl-millet-laddu-box.jpeg",
    price: 50,
    rating: 4.8,
    unit: "5 pcs / 100 g",
    category: "Millet Laddu",
  },
  {
    id: 34,
    name: "Multi Millet laddu Box",
    image: "/products/Millet Laddu/multi-millet-laddu-box.jpeg",
    price: 50,
    rating: 4.7,
    unit: "5 pcs / 100 g",
    category: "Millet Laddu",
  },
  {
    id: 35,
    name: "Finger Millet laddu Box",
    image: "/products/Millet Laddu/finger-millet-laddu-box.jpeg",
    price: 50,
    rating: 4.9,
    unit: "5 pcs / 100 g",
    category: "Millet Laddu",
    isBestSeller: true,
  },
  {
    id: 36,
    name: "Green Gram Millet laddu Box",
    image: "/products/Millet Laddu/green-gram-laddu-box.jpeg",
    price: 60,
    rating: 4.8,
    unit: "5 pcs / 100 g",
    category: "Millet Laddu",
  },
  {
    id: 37,
    name: "Black Gram Millet laddu Box",
    image: "/products/Millet Laddu/black-gram-laddu-box.jpeg",
    price: 60,
    rating: 4.7,
    unit: "5 pcs / 100 g",
    category: "Millet Laddu",
  },
  {
    id: 38,
    name: "Pearl Millet laddu Jar",
    image: "/products/Millet Laddu/pearl-millet-laddu-jar.png",
    price: 200,
    rating: 4.9,
    unit: "20 pcs / 400 g",
    category: "Millet Laddu",
  },
  {
    id: 39,
    name: "Multi Millet laddu Jar",
    image: "/products/Millet Laddu/multi-millet-laddu-jar.jpeg",
    price: 200,
    rating: 4.8,
    unit: "20 pcs / 400 g",
    category: "Millet Laddu",
  },
  {
    id: 40,
    name: "Finger Millet laddu Jar",
    image: "/products/Millet Laddu/finger-millet-laddu-jar.jpeg",
    price: 200,
    rating: 4.9,
    unit: "20 pcs / 400 g",
    category: "Millet Laddu",
  },
  {
    id: 41,
    name: "Green Gram Millet laddu Jar",
    image: "/products/Millet Laddu/green-gram-laddu-jar.jpeg",
    price: 240,
    rating: 4.8,
    unit: "20 pcs / 400 g",
    category: "Millet Laddu",
  },
  {
    id: 42,
    name: "Black Gram Millet laddu Jar",
    image: "/products/Millet Laddu/black-gram-laddu-jar.jpeg",
    price: 240,
    rating: 4.7,
    unit: "20 pcs / 400 g",
    category: "Millet Laddu",
  },
];

let CATEGORIES = [];

PRODUCTS.forEach((p) => {
  if (!CATEGORIES.includes(p.category)) {
    CATEGORIES.push(p.category);
  }
});

export { PRODUCTS, CATEGORIES };
